### ISSUE TITLE
Tracking: View Component V3

### ISSUE THREAD

**Issue by BlakeWilliams** [ViewComponent/view_component#617]
This issue is for tracking the work required to get the library ready for a V3 release! If you have thoughts or feedback that is relevant to the V3 release (such as breaking changes), please comment here or open an issue referencing this issue.

## Goals
- [ ] ~[Components + View Colocation (Moving components to `app/views`)](https://github.com/github/view_component/issues/618)~
- [ ] ~[Add a caching API for view-components](https://github.com/github/view_component/issues/234)~
- [x] Documentation modernization (site)
- [x] #473
- [x] #620
- [x] [Deprecate Slots V1](https://github.com/github/view_component/issues/621) and promote Slots V2 to a default feature of components
- [x] #623
- [x] [Add `with_content` API](https://github.com/github/view_component/pull/534)
- [ ] ~[CSS encapsulation](https://github.com/github/view_component/pull/677)~
- [x] New slot setter/getter API (for `with_content` compatibility) #1262
- [x] #1042
- [x] #904
- [x] Breaking change #361 
- [ ] Remove `rendered_component` #1380
- [x] Turn on `render_preview` by default
- [ ] Add better test examples around rendered_content vs. page to make sure the latter is viable
- [x] Strip whitespace from templates by default https://github.com/github/view_component/pull/1379
- [x] Deprecate support of Ruby < 2.7
- [x] [Move repo to separate org](https://github.com/github/view_component/issues/1424)
- [x] Clarify EOL policy for Rails dependency

## Communication

- [ ] Share with contact at Ruby Weekly
- [ ] Publish on Rubyland news
- [ ] Internal engineering-wide post

**Comment by jesster2k10** [comment]
Hey, I'm interested in seeing how the CSS Encapsulation would look like. Are there any ideas so far?

**Comment by Spone** [comment]
> Hey, I'm interested in seeing how the CSS Encapsulation would look like. Are there any ideas so far?

Hi @jesster2k10 here is the related PR: https://github.com/github/view_component/pull/677

**Comment by BlakeWilliams** [comment]
@boardfish 👋 just a heads-up, but we're hoping to finalize v3 around April 2022 that will include your work on the generators.

**Comment by BlakeWilliams** [comment]
also cc @elia and @franks921, I added two items that have you assigned as owners. No pressure though, we're happy to help out where we can with that work.

**Comment by franks921** [comment]
> also cc @elia and @franks921, I added two items that have you assigned as owners. No pressure though, we're happy to help out where we can with that work.

Hi @BlakeWilliams 

Unfortunately, I'm still working through a heavy workload and my time is limited. I should be able to have a look in the next 2 weeks or so. Apologies if this is causing any delays

**Comment by BlakeWilliams** [comment]
> Unfortunately, I'm still working through a heavy workload and my time is limited. I should be able to have a look in the next 2 weeks or so. Apologies if this is causing any delays

Not at all, and like I said, no pressure! If you won't be able to get to it let us know, not a big deal at all. 🙂

**Comment by elia** [comment]
@BlakeWilliams just out of curiosity, any reason we're a _tracking issue_ instead of  a milestone (or both)?

**Comment by Spone** [comment]
@elia @BlakeWilliams I'd be happy to convert this to a Milestone if you think it's a good idea. In my opinion it would make things clearer :)

**Comment by joelhawksley** [comment]
@elia @Spone we generally just use tracking issues for this kind of thing internally ❤️
